### ISSUE TITLE
Possible bug caused by using " " as message on argument completion (*)

### ISSUE THREAD

**Issue by kastiglione** [keith/zsh-xcode-completions#2]
In this project, the `_arguments` function is generally given an argument completion in the form of:

```
*: :->action
```

Why is the message a single space?

Currently, when I do `xcodebuild -<TAB>`, I get 162 lines of output. The output consists of all options, plus their descriptions being listed on their own line with a `--` prefix, plus a bunch of blank lines, and all of this gets repeated three times.

When I changed [this line of `_xcodebuild`](https://github.com/keith/zsh-xcode-completions/blob/bb7da535b893b6494754a52d070b60d055ad2060/src/_xcodebuild#L56) to:

```
*::->actions
```

the use of an empty message, instead of one space, caused the tab completion of `-` options to work as expected.

I'm using zsh version 5.0.5.

**Comment by keith** [comment]
I can look into that, maybe the commit messages as well. I don't remember exactly but I believe that was required for something...

**Comment by kastiglione** [comment]
The closest thing that appears to be related, but not quite the same is: 0ae37347c55c96b83bc820a6766200547450ff60. It seems all files have had a single space message from the start.

**Comment by keith** [comment]
Interesting, as long as all the mentioned combinations worked it should be fine. I remember at some point there being an issue with the cases of:

1) `xcodebuild ACTION -<TAB>`
2) `xcodebuild -<TAB> AC<TAB>`
3) `xcodebuild -arg ACTION -<TAB>`

As long as those still work without that space then we're good!

**Comment by kastiglione** [comment]
According to `man zshcompsys`, there are three forms:

```
*:message:action
*::message:action
*:::message:action
```

and so `*::->actions` is perhaps being interpreted as the second with a message of "->actions".

Which puts me back to the start, getting bad completion for `-` options.

**Comment by keith** [comment]
Hmm. I wonder if the original issue you mention here of getting so many lines is caused by that, or a config issue on one of our sides. Here's what I get:

<img width="775" alt="screen shot 2016-02-21 at 11 04 42" src="https://cloud.githubusercontent.com/assets/283886/13204684/08f0968e-d88b-11e5-913e-84942079eb48.png">

**Comment by kastiglione** [comment]
I'll move my config files aside and try with defaults.

**Comment by kastiglione** [comment]
This line in my `.zshrc` is part of the problem:

``` sh
zstyle ':completion:*' matcher-list '' '+m:{[:lower:]}={[:upper:]}'
```

This is added by `compinstall`. I don't do any other customization, it's just this one line, which allows lower-to-upper matching when doing completion. I have no idea why these two things would conflict.

**Comment by keith** [comment]
Interesting. I don't either. Does the change your suggesting have any negative effects though? Because if it doesn't we could definitely merge it regardless.

**Comment by kastiglione** [comment]
Yeah, it made autocomplete half broken. I'm hoping to play around with this more over time to figure out a working fix.

**Comment by keith** [comment]
Let me know what you find!

**Comment by PatTheMav** [comment]
@keith I did try out your completions for the first time today and ran into similar issues, mainly when providing a single hyphen Zsh provided me with 186 completions, which were made up of:

* Normal arguments
* Lots of empty lines
* The `n` argument
* Lots of empty lines
* Description strings of the normal arguments

I dug into the script and found that the correct way to offer completion for the actions as well as correct completion of all arguments even with complex completion setups is to call the `_actions` function directly and _not_ use a state switch:

```
_arguments \
[...]
  ':*:Build actions:_actions
```

I gleaned this from other Zsh completions and at least in my tests it fixed all my issues:

* The actions are correctly suggested when no hyphen is provided
* The normal set of arguments is provided when a hyphen is provided, `-n` and `-dry-run` are correctly grouped
* State-based completions still work
* Partial completions work
* Actions are provided regardless of place in the command line (before and after arguments are provided)

I dunno if the _position_ in the `_arguments` call is of significance, but I moved it to the bottom of the call for now.

**Comment by keith** [comment]
def happy to take PRs, I haven't debugged this in a while  😕

**Comment by PatTheMav** [comment]
> def happy to take PRs, I haven't debugged this in a while 😕

Opened https://github.com/keith/zsh-xcode-completions/pull/16 to fix this.

**Comment by keith** [comment]
Thanks!
