### ISSUE TITLE
Xcodebuild

### ISSUE THREAD

**Issue by Bluelich** [keith/zsh-xcode-completions#4]
The command named `xcodebuild`  update to a new version since Xcode 8.3 was released!
`-exportOptionsPlist` is a newer option which was added to `xcodebuild` when Xcode 8.3 was released , and  `-exportFormat` is deprecated now!
Can you update this repo to  compatible with the newer `xcodebuild`?

**Comment by keith** [comment]
Awesome thanks yet! I can try and get to this soon. Feel free to submit a PR in the meantime if you have a chance!

**Comment by keith** [comment]
Feel free to submit something supporting this!
